### PR TITLE
Switch to yt-dlp

### LINKED ISSUE #27: Replace youtube-dl with yt-dlp
Related issue, which should be implemented or closed to close this issue: https://github.com/yausername/youtubedl-android/issues/117

### PR DESCRIPTION
**Pull request by xibr**
Switch to yt-dlp Fixes #27

### CODE REVIEW

**Review by yausername — APPROVED** [review]
LGTM
Thanks

**Comment by xibr** [comment]
@yausername Should the [full_description.txt](https://github.com/yausername/dvd/blob/master/fastlane/metadata/android/en-US/full_description.txt) file be updated? before bump version! 

If yes, should it be like this or do you have another suggestion!
```diff
diff --git a/fastlane/metadata/android/en-US/full_description.txt b/fastlane/metadata/android/en-US/full_description.txt
index 5c62925..581ed77 100644
--- a/fastlane/metadata/android/en-US/full_description.txt
+++ b/fastlane/metadata/android/en-US/full_description.txt
@@ -1,12 +1,12 @@
-📀 Video downloader app powered by youtube-dl.
+📀 Video downloader app powered by yt-dlp (formerly youtube-dl).
 
 🚀 Features
-* Download video/audio from 1000+ sites supported by youtube-dl.
-* Run custom youtube-dl commands.
-* Update youtube-dl version from settings.
+* Download video/audio from 1000+ sites supported by yt-dlp.
+* Run custom yt-dlp commands.
+* Update yt-dlp version from settings.
 * Share link via other apps.
 
 🔗 References
 * dvd - https://github.com/yausername/dvd
 * youtubedl-android - https://github.com/yausername/youtubedl-android
-* youtube-dl - https://github.com/ytdl-org/youtube-dl
+* yt-dlp - https://github.com/yt-dlp/yt-dlp (formerly youtube-dl - https://github.com/ytdl-org/youtube-dl)
```

**Comment by yausername** [comment]
yeah this looks good to me. To release a new version on fdriod we would need to update [this](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.yausername.dvd.yml) file as well.
I'm guessing this is a breaking change and people who upgrade from previous versions might have to clear data first. If that's the case, it might be good to also add a changelog file for the new version as described in the fastlane section [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/). In the changelog file we can say that users need to uninstall pervious version or clear data for this update to work.

**Comment by xibr** [comment]
> To release a new version on fdriod we would need to update [this](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.yausername.dvd.yml) file as well.

Well, I'll take a look at it tomorrow, if you have time, please feel free to do it.
>  I'm guessing this is a breaking change and people who upgrade from previous versions might have to clear data first. If that's the case, it might be good to also add a changelog file for the new version as described in the fastlane section [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/).

it's not required.

**Comment by xibr** [comment]
Hi @yausername I have updated [org.yausername.dvd.yml](https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/org.yausername.dvd.yml) in the merge request[!10208](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10208) But 0.1.3 hasn't been released yet, is there anything else to do?

**Comment by yausername** [comment]
It can take some time for the release to happen because fdroid does some manual sigining process. We should wait a few more days. https://monitor.f-droid.org/builds/needsupdate

**Pull request merged**
